titulo_sitio: "Resume - Start Bootstrap Theme"
datos_personales:
  foto: "profile.jpg"
  persona:
    - nombre: "Clarence"
    - apellido: "Taylor"
  direccion:
    - calle: "3542 Berry Street"
    - poblacion: "Cheyenne Wells, CO 80810"
    - telefono: "(317) 585-8468"
    - correo: "name@email.com"
contenido:
  about:
    - type: "paragraph"
      value: "I am experienced in leveraging agile frameworks to provide a robust synopsis for high level overviews. Iterative approaches to corporate strategy foster collaborative thinking to further the overall value proposition."
  experience:
    element1:
      - type: "header"
        text: "Senior Web Developer"
      - type: "subheader"
        text: "Intelitec Solutions"
      - type: "paragraph"
        text: "Bring to the table win-win survival strategies to ensure proactive domination. At the end of the day, going forward, a new normal that has evolved from generation X is on the runway heading towards a streamlined cloud solution. User generated content in real-time will have multiple touchpoints for offshoring."
      - type: "date"
        text: "March 2013 - Present"
    element2:
      - type: "header"
        text: "Web Developer"
      - type: "subheader"
        text: "Intelitec Solutions"
      - type: "paragraph"
        text: "Capitalize on low hanging fruit to identify a ballpark value added activity to beta test. Override the digital divide with additional clickthroughs from DevOps. Nanotechnology immersion along the information highway will close the loop on focusing solely on the bottom line."
      - type: "date"
        text: "December 2011 - March 2013"
    element3:
      - type: "header"
        text: "Junio Web Designer"
      - type: "subheader"
        text: "Shout! Media Productions"
      - type: "paragraph"
        text: "Podcasting operational change management inside of workflows to establish a framework. Taking seamless key performance indicators offline to maximise the long tail. Keeping your eye on the ball while performing a deep dive on the start-up mentality to derive convergence on cross-platform integration."
      - type: "date"
        text: "July 2010 - December 2011"
    element4:
      - type: "header"
        text: "Web Design Intern"
      - type: "subheader"
        text: "Shout! Media Productions"
      - type: "paragraph"
        text: "Collaboratively administrate empowered markets via plug-and-play networks. Dynamically procrastinate B2C users after installed base benefits. Dramatically visualize customer directed convergence without revolutionary ROI."
      - type: "date"
        text: "September 2008 - June 2010"
  education:
    element5:
      - type: "header"
        text: "University of Colorado Boulder"
      - type: "subheader"
        text: "Bachelor of Science"
      - type: "paragraph"
        text: "Computer Science - Web Development Track"
      - type: "subparagraph"
        text: "GPA: 3.23"
      - type: "date"
        text: "August 2006 - May 2010"
    element6:
      - type: "header"
        text: "James Buchanan High School"
      - type: "subheader"
        text: "Technology Magnet Program"
      - type: "paragraph"
        text: ""
      - type: "subparagraph"
        text: "GPA: 3.56"
      - type: "date"
        text: "August 2002 - May 2006"
# a partir de aquí ya no se los comparto para que lo hagan
  interests:
    - type: "paragraph"
      value: "Apart from being a web developer, I enjoy most of my time being outdoors. In the winter, I am an avid skier and novice ice climber. During the warmer months here in Colorado, I enjoy mountain biking, free climbing, and kayaking."
    - type:  "paragraph"
      value: "When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows, I am an aspiring chef, and I spend a large amount of my free time exploring the latest technology advancements in the front-end web development world."
  awards:
    - "Google Analytics Certified Developer"
    - "Mobile Web Specialist - Google Certification"
    - "1 <sup>st</sup> Place - University of Colorado Boulder - Emerging Tech Competition 2009"
    - "1 <sup>st</sup>  Place - University of Colorado Boulder - Adobe Creative Jam 2008 (UI Design Category)"
    - "2 <sup>nd</sup>  Place - University of Colorado Boulder - Emerging Tech Competition 2008"
    - "1 <sup>st</sup>  Place - James Buchanan High School - Hackathon 2006"
    - "3 <sup>rd</sup>  Place - James Buchanan High School - Hackathon 2005"
  workflow:
    - "Mobile-First, Responsive Design"
    - "Cross Browser Testing & Debugging"
    - "Cross Functional Teams"
    - "Agile Development & Scrum"
    - "profa courses"
  languages:
    - "fa-html5"
    - "fa-css3-alt"
    - "fa-js-square"
    - "fa-angular"
    - "fa-react"
    - "fa-node-js"
    - "fa-sass"
    - "fa-less"
    - "fa-wordpress"
    - "fa-gulp"
    - "fa-grunt"
    - "fa-npm"
    - "fa-python"